---
openapi: 3.0.0
info:
  title: pokeTrade
  description: This API provides audit info
  contact:
    email: agraystone@bcit.ca
  version: 1.0.0

paths:
  /posttrade:
    get:
      summary: gets a posted trade from history
      operationId: app.get_posted_trade
      description: Gets posted trades from the event store
      parameters:
        - name: index
          in: query
          description: gets the posted trade at the index in the event store
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: Successfully returned a posted trade event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/PostTrade'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /accepttrade:
    get:
      summary: gets accepted trades from history
      operationId: app.get_accepted_trade
      description: Gets accepted trades from the event store
      parameters:
        - name: index
          in: query
          description: gets the accepted trade at the index in the event store
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: Successfully returned an accepted trade
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/AcceptTrade'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /health:
    get:
      tags:
        - health
      summary: health endpoint
      operationId: app.health_check
      description: health check
      responses:
        '200':
          description: service is healthy
          
components:
  schemas:
    PostTrade:
      required:
      - pokemon_happiness
      - pokemon_level
      - pokemon_to_trade
      - trade_accepted
      - trade_id
      - pokemon_def
      - pokemon_speed
      - trace_id
      type: object
      properties:
        trade_id:
          type: integer
        pokemon_to_trade:
          type: string
          example: Pikachu
        pokemon_level:
          type: integer
        pokemon_happiness:
          type: integer
        trade_accepted:
          type: string
        pokemon_def:
          type: integer
        pokemon_speed:
          type: integer
        trace_id:
          type: integer
    AcceptTrade:
      required:
      - pokemon_atk
      - pokemon_happiness
      - pokemon_hp
      - pokemon_level
      - pokemon_to_accept
      - accepted_trade_id
      - username
      - trace_id
      type: object
      properties:
        accepted_trade_id:
          type: integer
        username:
          type: string
          example: example123
        pokemon_to_accept:
          type: string
          example: Bulbasaur
        pokemon_level:
          type: integer
        pokemon_happiness:
          type: string
        pokemon_hp:
          type: integer
        pokemon_atk:
          type: integer
        trace_id:
          type: integer

