---
openapi: 3.0.0
info:
  title: Health API
  description: This API provides health monitoring
  contact:
    email: agraystone@bcit.ca
  version: 1.0.0
servers:
- url: http://localhost:8120
paths:
    get:
      tags:
        - health
      summary: health endpoint
      operationId: app.health_check
      description: health check
      responses:
        '200':
          description: service is healthy
          content:
            text/plain:
              schema:
                type: string
