---
openapi: 3.0.0
info:
  title: Health API
  description: This API provides health monitoring
  contact:
    email: agraystone@bcit.ca
  version: 1.0.0
servers:
- url: http://localhost:8120
paths:
  /health:
    get:
      tags:
        - health
      summary: health endpoint
      operationId: app.health_check
      description: health check
      responses:
        '200':
          description: Successfully returned a list of health checks
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/HealthCheck'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    HealthCheck:
      required:
        - receiver:
          type: string
        - storage:
          type: string
        - processing:
          type: string
        - audit:
          type: string
        - last_update:
          type: string
      type: object
